version: 43.0.9
pageUuid: 39347700-aacd-11ec-ae09-57783064a589
appTemplate:
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
  rootScreen: null
  isFetching: true
  version: 2.100.7
