version: 43.0.9
pageUuid: c20b1d76-0a9c-11ec-81b0-d370c741a3b7
appTemplate:
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
  queryStatusVisibility: true
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
      serverDepGraphEnabled: false
      useRuntimeV2: false
  version: 3.4.3
  markdownLinkBehavior: never
