version: 43.0.9
pageUuid: e66939a0-b9ce-11ec-9bcd-9737469c5da3
appTemplate:
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
  rootScreen: null
  isGlobalWidget: true
  version: 2.95.3
  markdownLinkBehavior: auto
