version: 43.0.9
pageUuid: cdc1d7c0-9027-11ec-b0c3-ab01646c36a6
appTemplate:
  folders:
    - new_version
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
  rootScreen: null
  version: 2.100.7
