id: PutValueSetToSimplifier
type: datasource
subtype: RESTQuery
resourceName: 3613b0ef-8f05-48f6-9c3c-d5a8bd47c43c
resourceDisplayName: FHIRRoninCommonModel
template:
  ordered:
    - queryRefreshTime: ''
    - paginationLimit: ''
    - body: '{{jsonEditor2.value}}'
    - lastReceivedFromResourceAt: null
    - queryDisabledMessage: ''
    - successMessage: ''
    - queryDisabled: ''
    - playgroundQuerySaveId: latest
    - resourceNameOverride: ''
    - runWhenModelUpdates: false
    - paginationPaginationField: ''
    - headers: >-
        [{"key":"Authorization","value":"Bearer
        {{GetToken.data.token}}"},{"key":"Accept","value":"application/fhir+json"},{"key":"Content-Type","value":"application/fhir+json"}]
    - showFailureToaster: true
    - paginationEnabled: false
    - query: ValueSet/{{jsonEditor2.value.id}}
    - playgroundQueryUuid: ''
    - playgroundQueryId: null
    - error: null
    - privateParams: []
    - runWhenPageLoadsDelay: ''
    - data: null
    - importedQueryInputs:
        ordered: []
    - isImported: false
    - showSuccessToaster: true
    - cacheKeyTtl: ''
    - cookies: ''
    - metadata: null
    - changesetObject: ''
    - errorTransformer: >-
        // The variable 'data' allows you to reference the request's data in the
        transformer. 

        // example: return data.find(element => element.isError)

        return data.error
    - confirmationMessage: null
    - isFetching: false
    - changeset: ''
    - rawData: null
    - queryTriggerDelay: '0'
    - resourceTypeOverride: null
    - watchedParams: []
    - enableErrorTransformer: false
    - showLatestVersionUpdatedWarning: false
    - paginationDataField: ''
    - timestamp: 0
    - importedQueryDefaults:
        ordered: []
    - enableTransformer: false
    - showUpdateSetValueDynamicallyToggle: true
    - runWhenPageLoads: false
    - transformer: >-
        // type your code here

        // example: return formatDataAsArray(data).filter(row => row.quantity >
        20)

        return data
    - events:
        - ordered:
            - event: success
            - type: util
            - method: showNotification
            - pluginId: ''
            - targetId: null
            - params:
                ordered:
                  - options:
                      ordered:
                        - notificationType: success
                        - title: >-
                            The Valueset {{Search.selectedLabel}} has been
                            uploaded to Simplifier
            - waitType: debounce
            - waitMs: '0'
        - ordered:
            - event: success
            - type: util
            - method: confetti
            - pluginId: ''
            - targetId: null
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
        - ordered:
            - event: success
            - type: widget
            - method: open
            - pluginId: modal1
            - targetId: null
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
        - ordered:
            - event: failure
            - type: util
            - method: showNotification
            - pluginId: ''
            - targetId: null
            - params:
                ordered:
                  - options:
                      ordered:
                        - notificationType: info
                        - title: >-
                            The Valueset {{Search.selectedLabel}} failed to
                            upload to Simplifier
            - waitType: debounce
            - waitMs: '0'
    - queryTimeout: '10000'
    - requireConfirmation: false
    - type: PUT
    - queryFailureConditions: ''
    - changesetIsObject: false
    - enableCaching: false
    - allowedGroups: []
    - bodyType: raw
    - queryThrottleTime: '750'
    - updateSetValueDynamically: false
    - notificationDuration: ''
createdAt: 2022-08-12T22:30:12.406Z
