version: 43.0.9
pageUuid: afb4d380-50cb-11ed-b76c-ffbcb400100c
appTemplate:
  folders:
    - ready_for_review_tab
    - no_map_concepts_tab
    - concepts_for_discussion
  rootScreen: null
  version: 2.100.7
  markdownLinkBehavior: auto
