version: 43.0.9
pageUuid: afb4d380-50cb-11ed-b76c-ffbcb400100c
appTemplate:
  mobileAppSettings:
    object:
      mobileOfflineModeEnabled: false
      mobileOfflineModeDelaySync: false
      displaySetting:
        object:
          landscapeMode: false
          tabletMode: false
  folders:
    - ready_for_review_tab
    - no_map_concepts_tab
    - concepts_for_discussion
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
      serverDepGraphEnabled: false
      useRuntimeV2: false
  version: 3.4.3
