version: 43.0.9
pageUuid: 429445c0-352c-11ed-a9cd-dfaacdcaa7fa
appTemplate:
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
      serverDepGraphEnabled: false
      useRuntimeV2: false
  rootScreen: null
  isGlobalWidget: true
  version: 2.110.3
  markdownLinkBehavior: auto
