version: 43.0.9
pageUuid: 429445c0-352c-11ed-a9cd-dfaacdcaa7fa
appTemplate:
  mobileAppSettings:
    object:
      mobileOfflineModeEnabled: false
      mobileOfflineModeDelaySync: false
      displaySetting:
        object:
          landscapeMode: false
          tabletMode: false
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
  queryStatusVisibility: true
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
      serverDepGraphEnabled: false
      useRuntimeV2: false
  isGlobalWidget: true
  version: 3.4.3
