version: 43.0.9
pageUuid: 35347ac0-9bf4-11ec-bea5-53c1223dcd2f
appTemplate:
  folders:
    - concept_map_queries
    - valueset_queries
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
  rootScreen: null
  version: 2.95.3
