version: 43.0.9
pageUuid: 2e4206c4-2228-11ec-99aa-e782eefccea2
appTemplate:
  mobileAppSettings:
    object:
      mobileOfflineModeEnabled: false
      mobileOfflineModeDelaySync: false
      displaySetting:
        object:
          landscapeMode: false
          tabletMode: false
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
  rootScreen: null
  version: 2.121.5
