version: 43.0.9
pageUuid: f6114ba0-3475-11ed-85a1-178db876f5ba
appTemplate:
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
  queryStatusVisibility: true
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
      serverDepGraphEnabled: false
      useRuntimeV2: false
  version: 3.4.3
