version: 43.0.9
pageUuid: e2acd320-3ab6-11ee-987c-7f06c8ab6b06
appTemplate:
  mobileAppSettings:
    object:
      mobileOfflineModeEnabled: false
      mobileOfflineModeDelaySync: false
      displaySetting:
        object:
          landscapeMode: false
          tabletMode: false
  appThemeId: -1
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
  queryStatusVisibility: true
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
      serverDepGraphEnabled: false
      useRuntimeV2: false
  version: 3.4.3
