version: 43.0.9
pageUuid: 0eaa8960-b6d5-11ed-8108-eff60e0cb731
appTemplate:
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
      serverDepGraphEnabled: false
      useRuntimeV2: false
  rootScreen: null
  isGlobalWidget: true
  version: 2.100.7
  markdownLinkBehavior: auto
