version: 43.0.9
pageUuid: bce32b40-a56f-11ec-b018-27b84d9f6b2f
appTemplate:
  folders:
    - Temporary state
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
  rootScreen: null
  version: 2.95.3
