version: 43.0.9
pageUuid: c887fbc0-839a-11ec-a584-93809bc5e41b
appTemplate:
  folders:
    - Temporary state
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
  rootScreen: null
  version: 2.95.3
