version: 43.0.9
pageUuid: e05e5e00-22d4-11ec-ac10-033a63082f03
appTemplate:
  mobileAppSettings:
    object:
      mobileOfflineModeEnabled: false
      mobileOfflineModeDelaySync: false
      displaySetting:
        object:
          landscapeMode: false
          tabletMode: false
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
  rootScreen: null
  version: 2.121.5
