version: 43.0.9
pageUuid: 5593da60-b510-11ec-ac15-97fd20062a3c
appTemplate:
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
  rootScreen: null
  version: 2.100.7
  markdownLinkBehavior: auto
