insert into concept_maps.concept_relationship
  (uuid, 
   concept_map_version_uuid, 
   review_status, 
   mapping_comments, 
   source_concept_uuid, 
   relationship_code_uuid, 
   target_concept_code, 
   target_concept_display, 
   target_concept_system, 
   target_concept_system_version_uuid, 
   created_date, author)
values
  ({{uuid.v4()}}, 
   {{urlparams.uuid}}, 
   'ready for review', 
   {{mapcomments.value}}, 
   {{source_concepts.selectedRow.data.uuid}}, 
   {{relationship_selection.value}}, 
   {{custom_terminology_table.selectedRow.data.code}},
   {{custom_terminology_table.selectedRow.data.display}},
   {{custom_terminology_selector.value}},
   {{custom_terminology_table.selectedRow.data.terminology_version}}, 
   now(),
   {{current_user.fullName}})